### ISSUE TITLE
ActivityNotFoundException

### ISSUE THREAD

**Issue by lingling-fan** [mafik/echo#10]
//package name: eu.mrogalski.saidit
//version: 1.3.38
 android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=eu.mrogalski.saidit }
 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1541)
 	at android.app.Activity.startActivityFromFragment(Activity.java:3917)
 	at android.app.Activity.startActivityFromFragment(Activity.java:3892)
 	at android.app.Fragment.startActivity(Fragment.java:1053)
 	at android.app.Fragment.startActivity(Fragment.java:1032)
 	at eu.mrogalski.saidit.l.onClick(SourceFile:215)
 	at android.view.View.performClick(View.java:4240)
 	at android.view.View.onKeyUp(View.java:7928)
 	at android.view.KeyEvent.dispatch(KeyEvent.java:2647)
 	at android.view.View.dispatchKeyEvent(View.java:7343)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.widget.ScrollView.dispatchKeyEvent(ScrollView.java:353)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1393)
 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:1933)
 	at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1408)
 	at android.app.Activity.dispatchKeyEvent(Activity.java:2384)
 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1860)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3791)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3774)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3483)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3540)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3516)
 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3666)
 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:1982)
 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1698)
 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1689)
 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:1959)
 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
 	at android.os.MessageQueue.nativePollOnce(Native Method)
 	at android.os.MessageQueue.next(MessageQueue.java:132)
 	at android.os.Looper.loop(Looper.java:124)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by mafik** [comment]
The stack trace is obfuscated and not usable for debugging. This is extra sus because official F-Droid builds don't use obfuscation. Somebody might have rebuilt it and my worry is that it may have some code injected. If it's still an issue for you, try reinstalling it from F-Droid.
