### ISSUE TITLE
java.lang.IllegalStateException: Not listening

### ISSUE THREAD

**Issue by lingling-fan** [mafik/echo#8]
//package name: eu.mrogalski.saidit
//version: 1.3.38
 java.lang.IllegalStateException: Not listening!
 	at eu.mrogalski.saidit.aa.run(SourceFile:394)
 	at android.app.Activity.runOnUiThread(Activity.java:4673)
 	at eu.mrogalski.saidit.z.a(SourceFile:384)
 	at eu.mrogalski.saidit.an.run(SourceFile:481)
 	at android.os.Handler.handleCallback(Handler.java:730)
 	at android.os.Handler.dispatchMessage(Handler.java:92)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by mafik** [comment]
See #10
